"""DDL generator for Snowflake infrastructure.

Generates all Snowflake DDLs from a UseCaseConfig:
- Database and schemas
- Stages for raw data
- Tables for curated data
- Cortex Search services
- State tables for orchestration
- ML model registry setup
"""

from pathlib import Path
from typing import List

from src.config import (
    UseCaseConfig,
    StructuredDataAsset,
    UnstructuredDataAsset,
    DataType,
    AgentType,
)


def generate_ddls(config: UseCaseConfig, output_dir: Path) -> List[Path]:
    """Generate all DDL files from a UseCaseConfig.
    
    Args:
        config: The use case configuration
        output_dir: Directory to write DDL files
        
    Returns:
        List of generated file paths
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    generated_files = []
    
    setup_ddl = _generate_setup_ddl(config)
    setup_path = output_dir / "01_setup.sql"
    setup_path.write_text(setup_ddl)
    generated_files.append(setup_path)
    
    stages_ddl = _generate_stages_ddl(config)
    stages_path = output_dir / "02_stages.sql"
    stages_path.write_text(stages_ddl)
    generated_files.append(stages_path)
    
    tables_ddl = _generate_tables_ddl(config)
    tables_path = output_dir / "03_tables.sql"
    tables_path.write_text(tables_ddl)
    generated_files.append(tables_path)
    
    state_ddl = _generate_state_tables_ddl(config)
    state_path = output_dir / "04_state_tables.sql"
    state_path.write_text(state_ddl)
    generated_files.append(state_path)
    
    if config.data.unstructured:
        cortex_ddl = _generate_cortex_search_ddl(config)
        cortex_path = output_dir / "05_cortex_search.sql"
        cortex_path.write_text(cortex_ddl)
        generated_files.append(cortex_path)
    
    ml_ddl = _generate_ml_ddl(config)
    ml_path = output_dir / "06_ml_setup.sql"
    ml_path.write_text(ml_ddl)
    generated_files.append(ml_path)
    
    return generated_files


def _generate_setup_ddl(config: UseCaseConfig) -> str:
    """Generate database and schema setup DDL."""
    db = config.snowflake.database
    
    schemas = [
        config.snowflake.raw_schema,
        config.snowflake.curated_schema,
        config.snowflake.ml_schema,
        config.snowflake.docs_schema,
        config.snowflake.analytics_schema,
        config.snowflake.cortex_schema,
        config.snowflake.orchestrator_schema,
    ]
    
    ddl = f"""-- =============================================================================
-- Database and Schema Setup for: {config.domain.name}
-- Generated by Agentic Platform
-- =============================================================================

-- Create database (if not exists)
CREATE DATABASE IF NOT EXISTS {db}
    COMMENT = '{config.domain.description[:100].replace("'", "''")}';

USE DATABASE {db};

-- Create schemas
"""
    
    for schema in schemas:
        ddl += f"CREATE SCHEMA IF NOT EXISTS {schema};\n"
    
    ddl += f"""
-- Set default schema
USE SCHEMA {config.snowflake.curated_schema};

-- Grant permissions (adjust roles as needed)
-- GRANT USAGE ON DATABASE {db} TO ROLE <your_role>;
-- GRANT USAGE ON ALL SCHEMAS IN DATABASE {db} TO ROLE <your_role>;
"""
    
    return ddl


def _generate_stages_ddl(config: UseCaseConfig) -> str:
    """Generate stage DDLs for raw data ingestion."""
    db = config.snowflake.database
    raw_schema = config.snowflake.raw_schema
    
    ddl = f"""-- =============================================================================
-- Stage Definitions for Raw Data
-- =============================================================================

USE DATABASE {db};
USE SCHEMA {raw_schema};

"""
    
    for asset in config.data.structured:
        if asset.location.startswith("@"):
            stage_name = asset.location.split("/")[0].replace("@", "").split(".")[-1]
            ddl += f"""-- Stage for {asset.name}
CREATE STAGE IF NOT EXISTS {stage_name}
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Raw data stage for {asset.name}';

"""
    
    for asset in config.data.unstructured:
        if asset.location.startswith("@"):
            stage_name = asset.location.split("/")[0].replace("@", "").split(".")[-1]
            ddl += f"""-- Stage for {asset.name} ({asset.doc_type.value} documents)
CREATE STAGE IF NOT EXISTS {stage_name}
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = '{asset.content_description[:100].replace("'", "''")}';

"""
    
    return ddl


def _generate_tables_ddl(config: UseCaseConfig) -> str:
    """Generate table DDLs for curated data."""
    db = config.snowflake.database
    curated_schema = config.snowflake.curated_schema
    
    ddl = f"""-- =============================================================================
-- Curated Data Tables
-- =============================================================================

USE DATABASE {db};
USE SCHEMA {curated_schema};

"""
    
    for asset in config.data.structured:
        if not asset.location.startswith("@"):
            table_name = asset.location.split(".")[-1]
            ddl += _generate_table_ddl(asset, table_name)
    
    return ddl


def _generate_table_ddl(asset: StructuredDataAsset, table_name: str) -> str:
    """Generate DDL for a single structured data asset."""
    columns = []
    
    if asset.time_column:
        columns.append(f"    {asset.time_column} TIMESTAMP_NTZ NOT NULL")
    
    if asset.entity_column and asset.entity_column not in [asset.time_column]:
        columns.append(f"    {asset.entity_column} VARCHAR(256) NOT NULL")
    
    for key_col in asset.key_columns:
        if key_col not in [asset.time_column, asset.entity_column]:
            columns.append(f"    {key_col} VARCHAR(256)")
    
    for measure in asset.measures:
        if measure not in asset.key_columns:
            columns.append(f"    {measure} FLOAT")
    
    for dim in asset.dimensions:
        if dim not in asset.key_columns and dim != asset.entity_column:
            columns.append(f"    {dim} VARCHAR(256)")
    
    if asset.label_column:
        columns.append(f"    {asset.label_column} BOOLEAN")
    
    columns.append("    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()")
    
    ddl = f"""-- Table: {table_name}
-- Type: {asset.data_type.value}
-- Volume: {asset.volume or 'unknown'}
CREATE TABLE IF NOT EXISTS {table_name} (
{','.join(chr(10) + col for col in columns)}
)
COMMENT = 'Curated {asset.data_type.value} data for {asset.name}';

"""
    
    if asset.time_column:
        ddl += f"""-- Clustering for time-series queries
ALTER TABLE {table_name} CLUSTER BY ({asset.time_column});

"""
    
    return ddl


def _generate_state_tables_ddl(config: UseCaseConfig) -> str:
    """Generate state management tables for orchestration."""
    db = config.snowflake.database
    schema = config.snowflake.orchestrator_schema
    
    ddl = f"""-- =============================================================================
-- Orchestration State Tables
-- =============================================================================

USE DATABASE {db};
USE SCHEMA {schema};

-- Execution plans table
CREATE TABLE IF NOT EXISTS EXECUTION_PLANS (
    plan_id VARCHAR(64) PRIMARY KEY,
    use_case VARCHAR(256),
    config_hash VARCHAR(64),
    plan_json VARIANT,
    status VARCHAR(32) DEFAULT 'pending',
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    completed_at TIMESTAMP_NTZ,
    error_message TEXT
)
COMMENT = 'Tracks execution plans for the meta-agent';

-- Phase state table
CREATE TABLE IF NOT EXISTS PHASE_STATE (
    phase_id VARCHAR(64) PRIMARY KEY,
    plan_id VARCHAR(64) REFERENCES EXECUTION_PLANS(plan_id),
    phase_name VARCHAR(128),
    phase_type VARCHAR(64),
    status VARCHAR(32) DEFAULT 'pending',
    inputs VARIANT,
    outputs VARIANT,
    started_at TIMESTAMP_NTZ,
    completed_at TIMESTAMP_NTZ,
    error_message TEXT
)
COMMENT = 'Tracks individual phase execution state';

-- Artifacts table
CREATE TABLE IF NOT EXISTS ARTIFACTS (
    artifact_id VARCHAR(64) PRIMARY KEY,
    plan_id VARCHAR(64) REFERENCES EXECUTION_PLANS(plan_id),
    phase_id VARCHAR(64) REFERENCES PHASE_STATE(phase_id),
    artifact_type VARCHAR(64),
    artifact_name VARCHAR(256),
    artifact_path VARCHAR(512),
    metadata VARIANT,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Tracks generated artifacts (models, services, code)';

-- Cortex call logs
CREATE TABLE IF NOT EXISTS CORTEX_CALL_LOGS (
    log_id VARCHAR(64) PRIMARY KEY,
    plan_id VARCHAR(64),
    phase_id VARCHAR(64),
    execution_id VARCHAR(64),
    call_type VARCHAR(32),
    model_name VARCHAR(128),
    prompt_text TEXT,
    prompt_tokens INTEGER,
    response_text TEXT,
    response_tokens INTEGER,
    total_tokens INTEGER,
    latency_ms INTEGER,
    status VARCHAR(32),
    error_message TEXT,
    metadata VARIANT,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Logs all Cortex LLM/Search/Analyst calls';

-- LangGraph checkpoints
CREATE TABLE IF NOT EXISTS LANGGRAPH_CHECKPOINTS (
    thread_id VARCHAR(64),
    checkpoint_ns VARCHAR(64) DEFAULT '',
    checkpoint_id VARCHAR(64),
    parent_checkpoint_id VARCHAR(64),
    checkpoint_type VARCHAR(32),
    checkpoint_data VARIANT,
    metadata VARIANT,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id)
)
COMMENT = 'LangGraph state checkpoints for resumable workflows';

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_plans_status ON EXECUTION_PLANS(status);
CREATE INDEX IF NOT EXISTS idx_phases_plan ON PHASE_STATE(plan_id);
CREATE INDEX IF NOT EXISTS idx_logs_plan ON CORTEX_CALL_LOGS(plan_id);
CREATE INDEX IF NOT EXISTS idx_checkpoints_thread ON LANGGRAPH_CHECKPOINTS(thread_id);
"""
    
    return ddl


def _generate_cortex_search_ddl(config: UseCaseConfig) -> str:
    """Generate Cortex Search service DDLs."""
    db = config.snowflake.database
    docs_schema = config.snowflake.docs_schema
    cortex_schema = config.snowflake.cortex_schema
    
    ddl = f"""-- =============================================================================
-- Cortex Search Services
-- =============================================================================

USE DATABASE {db};
USE SCHEMA {docs_schema};

"""
    
    for asset in config.data.unstructured:
        chunks_table = f"{asset.name.upper()}_CHUNKS"
        service_name = f"{asset.name.upper()}_SEARCH_SERVICE"
        
        ddl += f"""-- Chunks table for {asset.name}
CREATE TABLE IF NOT EXISTS {chunks_table} (
    chunk_id VARCHAR(64) PRIMARY KEY,
    document_id VARCHAR(256),
    document_name VARCHAR(512),
    chunk_index INTEGER,
    chunk_text TEXT,
    section VARCHAR(256),
    metadata VARIANT,
    embedding VECTOR(FLOAT, 768),
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Document chunks for {asset.name} ({asset.doc_type.value})';

"""
    
    ddl += f"""
USE SCHEMA {cortex_schema};

"""
    
    for i, asset in enumerate(config.data.unstructured):
        chunks_table = f"{asset.name.upper()}_CHUNKS"
        service_name = f"{asset.name.upper()}_SEARCH_SERVICE"
        
        search_service = None
        for svc in config.cortex_services.search:
            if svc.source == asset.name:
                search_service = svc
                break
        
        columns_to_return = ["document_name", "chunk_text", "section"]
        if search_service and search_service.columns_to_return:
            columns_to_return = search_service.columns_to_return
        
        ddl += f"""-- Cortex Search service for {asset.name}
CREATE OR REPLACE CORTEX SEARCH SERVICE {service_name}
    ON chunk_text
    ATTRIBUTES section, document_name
    WAREHOUSE = ${{warehouse}}
    TARGET_LAG = '1 hour'
    AS (
        SELECT 
            chunk_id,
            document_name,
            chunk_text,
            section,
            metadata
        FROM {docs_schema}.{chunks_table}
    )
COMMENT = 'Semantic search over {asset.content_description[:50]}';

"""
    
    return ddl


def _generate_ml_ddl(config: UseCaseConfig) -> str:
    """Generate ML infrastructure DDLs."""
    db = config.snowflake.database
    ml_schema = config.snowflake.ml_schema
    
    ddl = f"""-- =============================================================================
-- ML Infrastructure
-- =============================================================================

USE DATABASE {db};
USE SCHEMA {ml_schema};

-- Model metrics tracking
CREATE TABLE IF NOT EXISTS MODEL_METRICS (
    metric_id VARCHAR(64) PRIMARY KEY,
    model_name VARCHAR(128),
    model_version VARCHAR(64),
    metric_name VARCHAR(64),
    metric_value FLOAT,
    dataset_type VARCHAR(32),
    evaluation_date TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    metadata VARIANT
)
COMMENT = 'Tracks ML model performance metrics';

-- Feature importance tracking
CREATE TABLE IF NOT EXISTS FEATURE_IMPORTANCE (
    id VARCHAR(64) PRIMARY KEY,
    model_name VARCHAR(128),
    model_version VARCHAR(64),
    feature_name VARCHAR(128),
    importance_score FLOAT,
    importance_rank INTEGER,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Feature importance scores for ML models';

-- Prediction logs
CREATE TABLE IF NOT EXISTS PREDICTION_LOGS (
    prediction_id VARCHAR(64) PRIMARY KEY,
    model_name VARCHAR(128),
    model_version VARCHAR(64),
    input_features VARIANT,
    prediction VARIANT,
    probability FLOAT,
    latency_ms INTEGER,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Logs model predictions for monitoring';

"""
    
    for model in config.ml_models:
        ddl += f"""-- Training data view for {model.name}
-- Source: {model.source_table}
-- Target: {model.target}
-- Task: {model.task.value}
-- Business Value: {model.business_value}
/*
CREATE OR REPLACE VIEW {model.name.upper()}_TRAINING_DATA AS
SELECT 
    {', '.join(model.features) if model.features else '*'},
    {model.target}
FROM {model.source_table}
WHERE {model.target} IS NOT NULL;
*/

"""
    
    return ddl
