spec:
  containers:
  - name: orchestrator
    image: /${DB}/${SCHEMA}/${IMAGE_REPO}/orchestrator:latest
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m
    readinessProbe:
      port: 8080
      path: /health
  endpoints:
  - name: app
    port: 8080
    public: true
