-- Setup SQL for Agentic Platform Orchestrator
-- Run this before deploying the orchestrator

-- Create database and schemas
CREATE DATABASE IF NOT EXISTS AGENTIC_PLATFORM;

CREATE SCHEMA IF NOT EXISTS AGENTIC_PLATFORM.ORCHESTRATOR;
CREATE SCHEMA IF NOT EXISTS AGENTIC_PLATFORM.RAW;
CREATE SCHEMA IF NOT EXISTS AGENTIC_PLATFORM.CURATED;
CREATE SCHEMA IF NOT EXISTS AGENTIC_PLATFORM.ML;
CREATE SCHEMA IF NOT EXISTS AGENTIC_PLATFORM.CORTEX;

-- Create workflow state table for persistence
CREATE TABLE IF NOT EXISTS AGENTIC_PLATFORM.ORCHESTRATOR.WORKFLOW_STATE (
    plan_id VARCHAR(100) PRIMARY KEY,
    state_json VARIANT,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create execution logs table
CREATE TABLE IF NOT EXISTS AGENTIC_PLATFORM.ORCHESTRATOR.EXECUTION_LOGS (
    log_id VARCHAR(100) DEFAULT UUID_STRING(),
    plan_id VARCHAR(100),
    task_id VARCHAR(100),
    level VARCHAR(20),
    message TEXT,
    timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    metadata VARIANT
);

-- Create artifacts table
CREATE TABLE IF NOT EXISTS AGENTIC_PLATFORM.ORCHESTRATOR.ARTIFACTS (
    artifact_id VARCHAR(100) DEFAULT UUID_STRING(),
    plan_id VARCHAR(100),
    task_id VARCHAR(100),
    artifact_type VARCHAR(50),
    artifact_name VARCHAR(255),
    artifact_path VARCHAR(1000),
    metadata VARIANT,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create compute pool if not exists (adjust instance family as needed)
CREATE COMPUTE POOL IF NOT EXISTS AGENTIC_COMPUTE_POOL
    MIN_NODES = 1
    MAX_NODES = 2
    INSTANCE_FAMILY = CPU_X64_S;

-- Grant necessary permissions
GRANT USAGE ON DATABASE AGENTIC_PLATFORM TO ROLE PUBLIC;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AGENTIC_PLATFORM TO ROLE PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA AGENTIC_PLATFORM.ORCHESTRATOR TO ROLE PUBLIC;

-- Create stage for semantic models and configs
CREATE STAGE IF NOT EXISTS AGENTIC_PLATFORM.CORTEX.SEMANTIC_MODELS;
CREATE STAGE IF NOT EXISTS AGENTIC_PLATFORM.ORCHESTRATOR.CONFIGS;

GRANT READ, WRITE ON STAGE AGENTIC_PLATFORM.CORTEX.SEMANTIC_MODELS TO ROLE PUBLIC;
GRANT READ, WRITE ON STAGE AGENTIC_PLATFORM.ORCHESTRATOR.CONFIGS TO ROLE PUBLIC;
