"""Configuration module for agentic platform."""

from .loader import (
    create_blank_template,
    get_template_path,
    list_templates,
    load_template,
    load_use_case_yaml,
    save_use_case_yaml,
    validate_yaml_file,
)
from .platform_config import (
    SnowflakeSettings,
    configure_from_use_case,
    get_settings,
    reset_settings,
    set_settings,
)
from .use_case_schema import (
    AgentSpec,
    AgentType,
    APIEndpoint,
    AppSpec,
    ComponentType,
    CortexAgentConfig,
    CortexAnalystModel,
    CortexSearchService,
    CortexServices,
    DataAssets,
    DataType,
    DeploymentConfig,
    DocumentType,
    Domain,
    Industry,
    MLModelSpec,
    MLTaskType,
    PageLayout,
    PageSpec,
    Persona,
    RealTimeConfig,
    SnowflakeConfig,
    StructuredDataAsset,
    UIComponent,
    UnstructuredDataAsset,
    UseCaseConfig,
    create_drilling_ops_example,
)

__all__ = [
    # Schema classes
    "UseCaseConfig",
    "Domain",
    "Industry",
    "Persona",
    "DataAssets",
    "StructuredDataAsset",
    "UnstructuredDataAsset",
    "DataType",
    "DocumentType",
    "AgentSpec",
    "AgentType",
    "MLModelSpec",
    "MLTaskType",
    "AppSpec",
    "PageSpec",
    "PageLayout",
    "UIComponent",
    "ComponentType",
    "APIEndpoint",
    "RealTimeConfig",
    "DeploymentConfig",
    "CortexServices",
    "CortexSearchService",
    "CortexAnalystModel",
    "CortexAgentConfig",
    "SnowflakeConfig",
    # Factory functions
    "create_drilling_ops_example",
    # Loader functions
    "load_use_case_yaml",
    "save_use_case_yaml",
    "load_template",
    "list_templates",
    "get_template_path",
    "create_blank_template",
    "validate_yaml_file",
    # Platform config
    "SnowflakeSettings",
    "get_settings",
    "set_settings",
    "configure_from_use_case",
    "reset_settings",
]
