-- State Tables for Snowflake Agentic Platform
-- Manages execution plans, phase state, checkpoints, artifacts, and observability

USE DATABASE AGENTIC_PLATFORM;
USE SCHEMA STATE;

-- 1. AGENT_EXECUTION_PLANS: Top-level execution plans generated by meta-agent
CREATE TABLE IF NOT EXISTS AGENT_EXECUTION_PLANS (
    plan_id VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    use_case_description TEXT NOT NULL,
    parsed_requirements VARIANT,
    data_assets VARIANT,
    execution_plan VARIANT NOT NULL,
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'running', 'completed', 'failed', 'cancelled')),
    approval_status VARCHAR(20) DEFAULT 'pending' CHECK (approval_status IN ('pending', 'approved', 'rejected')),
    approved_by VARCHAR(100),
    approved_at TIMESTAMP_NTZ,
    error_message TEXT,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    completed_at TIMESTAMP_NTZ,
    created_by VARCHAR(100) DEFAULT CURRENT_USER()
);

COMMENT ON TABLE AGENT_EXECUTION_PLANS IS 'Top-level execution plans generated by meta-agent from use case descriptions';

-- 2. AGENT_PHASE_STATE: Phase-level state within an execution plan
CREATE TABLE IF NOT EXISTS AGENT_PHASE_STATE (
    phase_id VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    plan_id VARCHAR(36) NOT NULL REFERENCES AGENT_EXECUTION_PLANS(plan_id),
    phase_name VARCHAR(100) NOT NULL,
    phase_order INTEGER NOT NULL,
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'failed', 'skipped')),
    input_artifacts VARIANT,
    output_artifacts VARIANT,
    config VARIANT,
    error_message TEXT,
    retry_count INTEGER DEFAULT 0,
    started_at TIMESTAMP_NTZ,
    completed_at TIMESTAMP_NTZ,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE AGENT_PHASE_STATE IS 'Phase-level execution state tracking (Discovery, Preprocessing, ML, etc.)';

CREATE INDEX IF NOT EXISTS idx_phase_plan ON AGENT_PHASE_STATE(plan_id);
CREATE INDEX IF NOT EXISTS idx_phase_status ON AGENT_PHASE_STATE(status);

-- 3. AGENT_EXECUTION_STATE: Sub-agent level state within a phase
CREATE TABLE IF NOT EXISTS AGENT_EXECUTION_STATE (
    execution_id VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    phase_id VARCHAR(36) NOT NULL REFERENCES AGENT_PHASE_STATE(phase_id),
    plan_id VARCHAR(36) NOT NULL REFERENCES AGENT_EXECUTION_PLANS(plan_id),
    agent_name VARCHAR(100) NOT NULL,
    agent_version VARCHAR(20),
    sub_state VARCHAR(50),
    state_data VARIANT,
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'failed', 'retrying')),
    error_message TEXT,
    error_details VARIANT,
    retry_count INTEGER DEFAULT 0,
    max_retries INTEGER DEFAULT 3,
    started_at TIMESTAMP_NTZ,
    completed_at TIMESTAMP_NTZ,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE AGENT_EXECUTION_STATE IS 'Sub-agent level execution state (e.g., parquet_processor SCAN/LOAD states)';

CREATE INDEX IF NOT EXISTS idx_exec_phase ON AGENT_EXECUTION_STATE(phase_id);
CREATE INDEX IF NOT EXISTS idx_exec_plan ON AGENT_EXECUTION_STATE(plan_id);
CREATE INDEX IF NOT EXISTS idx_exec_agent ON AGENT_EXECUTION_STATE(agent_name);

-- 4. LANGGRAPH_CHECKPOINTS: LangGraph checkpoint persistence for resumability
CREATE TABLE IF NOT EXISTS LANGGRAPH_CHECKPOINTS (
    checkpoint_id VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    thread_id VARCHAR(100) NOT NULL,
    parent_checkpoint_id VARCHAR(36),
    checkpoint_data VARIANT NOT NULL,
    metadata VARIANT,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE LANGGRAPH_CHECKPOINTS IS 'LangGraph checkpoint persistence for execution resumability';

CREATE INDEX IF NOT EXISTS idx_checkpoint_thread ON LANGGRAPH_CHECKPOINTS(thread_id);
CREATE INDEX IF NOT EXISTS idx_checkpoint_parent ON LANGGRAPH_CHECKPOINTS(parent_checkpoint_id);

-- 5. AGENT_ARTIFACTS: Registry of all created artifacts (tables, models, services)
CREATE TABLE IF NOT EXISTS AGENT_ARTIFACTS (
    artifact_id VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    plan_id VARCHAR(36) REFERENCES AGENT_EXECUTION_PLANS(plan_id),
    phase_id VARCHAR(36) REFERENCES AGENT_PHASE_STATE(phase_id),
    artifact_type VARCHAR(50) NOT NULL CHECK (artifact_type IN (
        'table', 'view', 'stage', 'file', 
        'ml_model', 'ml_model_version', 'feature_store',
        'cortex_search_service', 'semantic_model', 'semantic_view',
        'spcs_service', 'spcs_image', 'compute_pool',
        'cortex_agent', 'app_spec', 'generated_code'
    )),
    artifact_name VARCHAR(500) NOT NULL,
    artifact_reference VARCHAR(1000) NOT NULL,
    metadata VARIANT,
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'deprecated', 'deleted')),
    created_by_agent VARCHAR(100),
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE AGENT_ARTIFACTS IS 'Registry of all artifacts created by agents (tables, models, services)';

CREATE INDEX IF NOT EXISTS idx_artifact_plan ON AGENT_ARTIFACTS(plan_id);
CREATE INDEX IF NOT EXISTS idx_artifact_type ON AGENT_ARTIFACTS(artifact_type);
CREATE INDEX IF NOT EXISTS idx_artifact_name ON AGENT_ARTIFACTS(artifact_name);

-- 6. CORTEX_CALL_LOGS: Observability for all Cortex LLM/Search calls
CREATE TABLE IF NOT EXISTS CORTEX_CALL_LOGS (
    log_id VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    plan_id VARCHAR(36) REFERENCES AGENT_EXECUTION_PLANS(plan_id),
    phase_id VARCHAR(36) REFERENCES AGENT_PHASE_STATE(phase_id),
    execution_id VARCHAR(36) REFERENCES AGENT_EXECUTION_STATE(execution_id),
    call_type VARCHAR(30) NOT NULL CHECK (call_type IN ('complete', 'search', 'embed', 'agent', 'analyst')),
    model_name VARCHAR(100),
    prompt_text TEXT,
    prompt_tokens INTEGER,
    response_text TEXT,
    response_tokens INTEGER,
    total_tokens INTEGER,
    latency_ms INTEGER,
    status VARCHAR(20) DEFAULT 'success' CHECK (status IN ('success', 'error', 'timeout')),
    error_message TEXT,
    metadata VARIANT,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE CORTEX_CALL_LOGS IS 'Observability logs for all Cortex LLM, Search, and Agent calls';

CREATE INDEX IF NOT EXISTS idx_log_plan ON CORTEX_CALL_LOGS(plan_id);
CREATE INDEX IF NOT EXISTS idx_log_type ON CORTEX_CALL_LOGS(call_type);
CREATE INDEX IF NOT EXISTS idx_log_created ON CORTEX_CALL_LOGS(created_at);

-- Views for monitoring

-- Active execution plans
CREATE OR REPLACE VIEW V_ACTIVE_PLANS AS
SELECT 
    plan_id,
    use_case_description,
    status,
    approval_status,
    created_at,
    DATEDIFF('minute', created_at, CURRENT_TIMESTAMP()) as minutes_elapsed
FROM AGENT_EXECUTION_PLANS
WHERE status IN ('pending', 'approved', 'running')
ORDER BY created_at DESC;

-- Phase progress summary
CREATE OR REPLACE VIEW V_PHASE_PROGRESS AS
SELECT 
    p.plan_id,
    e.use_case_description,
    p.phase_name,
    p.phase_order,
    p.status,
    p.retry_count,
    p.started_at,
    p.completed_at,
    DATEDIFF('second', p.started_at, COALESCE(p.completed_at, CURRENT_TIMESTAMP())) as duration_seconds
FROM AGENT_PHASE_STATE p
JOIN AGENT_EXECUTION_PLANS e ON p.plan_id = e.plan_id
ORDER BY p.plan_id, p.phase_order;

-- Cortex usage summary
CREATE OR REPLACE VIEW V_CORTEX_USAGE AS
SELECT 
    DATE_TRUNC('hour', created_at) as hour,
    call_type,
    model_name,
    COUNT(*) as call_count,
    SUM(total_tokens) as total_tokens,
    AVG(latency_ms) as avg_latency_ms,
    SUM(CASE WHEN status = 'error' THEN 1 ELSE 0 END) as error_count
FROM CORTEX_CALL_LOGS
GROUP BY 1, 2, 3
ORDER BY 1 DESC, 2;

-- Artifact inventory
CREATE OR REPLACE VIEW V_ARTIFACT_INVENTORY AS
SELECT 
    artifact_type,
    COUNT(*) as count,
    MAX(created_at) as latest_created
FROM AGENT_ARTIFACTS
WHERE status = 'active'
GROUP BY artifact_type
ORDER BY count DESC;
